apiVersion: v1
kind: Service
metadata:
  name: {{ template "cdl-api.fullname" . }}
  labels: {{ include "cdl-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-proxy
      protocol: TCP
      name: http
  selector: {{- include "cdl-api.serviceSelectorLabels" . | nindent 4 }}
