{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cdl-api.serviceAccountName" . }}
  labels: {{- include "cdl-api.labels" . | nindent 4 }}
{{- end -}}
