// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Confirmit.Cdl.Api.Controllers.AliasesController.GetAliasesAsync(System.Int32,System.Int32,System.String,System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Confirmit.Cdl.Api.Controllers.ArchivedDocumentsController.GetDeletedDocumentsAsync(System.Int32,System.Int32,System.String,System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Confirmit.Cdl.Api.Controllers.CommitsController.GetCommitsAsync(System.Int64,System.Int32,System.Int32,System.String,System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Confirmit.Cdl.Api.Controllers.CompanyPermissionsController.GetAllCompaniesAsync(System.Int64,System.Int32,System.Int32,System.String,System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Confirmit.Cdl.Api.Controllers.CompanyPermissionsController.GetCompanyPermissionsAsync(System.Int64,System.Int32,System.Int32,System.String,System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Confirmit.Cdl.Api.Controllers.DocumentsController.GetAccessedDocumentsAsync(System.Int32,System.Int32,System.String,System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Confirmit.Cdl.Api.Controllers.DocumentsController.GetDocumentsAsync(System.Int32,System.Int32,System.String,System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Confirmit.Cdl.Api.Controllers.EnduserListPermissionsController.GetAllEnduserListsAsync(System.Int64,System.Int32,System.Int32,System.String,System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Confirmit.Cdl.Api.Controllers.EnduserListPermissionsController.GetEnduserListPermissionsAsync(System.Int64,System.Int32,System.Int32,System.String,System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Confirmit.Cdl.Api.Controllers.EnduserPermissionsController.GetEnduserPermissionsAsync(System.Int64,System.Int32,System.Int32,System.String,System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Confirmit.Cdl.Api.Controllers.EnduserPermissionsController.GetEnduserPermissionsEnduserListsAsync(System.Int64,System.Int32,System.Int32,System.String,System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Confirmit.Cdl.Api.Controllers.EnduserPermissionsController.GetEnduserPermissionsForEnduserListAsync(System.Int64,System.Int32,System.Int32,System.Int32,System.String,System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Confirmit.Cdl.Api.Controllers.UserPermissionsController.GetUserPermissionsAsync(System.Int64,System.Int32,System.Int32,System.String,System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Confirmit.Cdl.Api.Controllers.UserPermissionsController.GetUserPermissionsCompaniesAsync(System.Int64,System.Int32,System.Int32,System.String,System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Confirmit.Cdl.Api.Controllers.RevisionsController.GetAccessedRevisionsAsync(System.Int32,System.Int32,System.String,System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Confirmit.Cdl.Api.Controllers.RevisionsController.GetDocumentRevisionsAsync(System.Int64,System.Int32,System.Int32,System.String,System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Confirmit.Cdl.Api.Controllers.RevisionsController.GetPublishedRevisionsAsync(System.Int32,System.Int32,System.String,System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]